### ISSUE TITLE
Need to write generic UCI/LCI variable definitions

### ISSUE THREAD

**Issue by ran-codes** [Drexel-UHC/salurbal-fair-renovations#101]
This is coming from a conversation from #26 but creating its own issue to track development. see the relevant conversation  copied over below:

---

> @juruchi @ran-codes I have a couple questions that will relate to both these childhood survey prevalence estimates and adult when ready.
> 
> 1. For each measure, there are 3 variables: the estimate (SVYXXX), Lower CI (SVYXXX_LCI), and Upper CI (SVYXXX_UCI). In the version of the 4.2-base__codebook.xlsx I'm reviewing only the estimate (SVYXXX) is included. Should I add rows for the LCI and UCI? Or would that be a strata?

 _Originally posted by @kam642 in https://github.com/Drexel-UHC/salurbal-fair-renovations/issues/26#issuecomment-1542647728_
 
---

>### UCI + LCI
>
>Good point Kari. To handle metadata for variables that have LCI/UCI we can do two things (on the top of my mind). 
>
>- **Option 1:** We can have generic UCI/LCI descriptions that can be used to describe all lci/uci columns. This will be compiled into the codebook if a variable has UCI/LC; meaning, the codebooks will have SVYXXX_LCI and SVIXXX_UCI . In this case **renovators do not fill this out; it is automatically compiled and sent to you/goro for review** 
>- **Option 2:** We can have `{var_name}_uci` and `{var_name}_lci` in the codebooks explicitly for each variable in the templates and **renovators fill these out then sent to you/goro for review.** 
>
>I am leaning towards Option 1. We could also do a mix of the both  if needed. Let me know what you think. 

_Originally posted by @ran-codes in https://github.com/Drexel-UHC/salurbal-fair-renovations/issues/26#issuecomment-1545741427_
            

---

 
>UCI + LCI - I like Option 1.
>
>Public - Public changes would be by country alone so would need to link by ISO.

_Originally posted by @kam642 in https://github.com/Drexel-UHC/salurbal-fair-renovations/issues/26#issuecomment-1545779256_
            
---

>Agree with option 1. Would this also apply to LE? there are also LCIs and UCIs there
>
_Originally posted by @usamabilal in https://github.com/Drexel-UHC/salurbal-fair-renovations/issues/26#issuecomment-1545813243_
            
---

>Yes this would be a generic mechanism that applies to all data that has LCU/UCI. Meaning the LCI/UCI language should be generic which we need to finalize at least for this release. Below is GPT4 draft. if you all want we can start there. 
>
>## GPT language
>
>**value_uci**: The 'value_uci' stands for Upper Confidence Interval, indicating the upper limit of the confidence range for the primary 'value'. This estimate provides an understanding of the statistical uncertainty surrounding the primary value, suggesting the highest possible accurate value.
>
>**value_lci**: The 'value_lci' refers to the Lower Confidence Interval, representing the lower limit of the confidence range for the primary 'value'. This value indicates the lowest possible accurate value within the confidence range, considering statistical uncertainty.

_Originally posted by @ran-codes in https://github.com/Drexel-UHC/salurbal-fair-renovations/issues/26#issuecomment-1545819656_
            
---

>The only issue I see is that these are quite different in SVY vs LE, right?
The SVI ones are prediction intervals, I think? They tell us the range that should contain the population prevalence  (calling @goro-yamada who teaches these things for an accurate interpretation!)
The LE ones are Bayesian credible intervals, telling us the range that contains 95% of the posterior distribution samples. 
>
>Their interpretation may be the same though, so we may be in the clear, but want to double check

_Originally posted by @usamabilal in https://github.com/Drexel-UHC/salurbal-fair-renovations/issues/26#issuecomment-1545823552_

**Comment by kam642** [comment]
@ran-codes Sorry it took me so long to open this and read it! I like the definitions - simple without having to explain Bayesian methods. No edits needed.

**Comment by ran-codes** [comment]
THanks @kam642.

closing no actions needed

**Comment by ran-codes** [comment]
Goro wants to update UCI and LCI. TBD whether its for the generic key-value pair ot to op. mortality specific key-value pairs [examples here](https://github.com/Drexel-UHC/salurbal-fair-renovations/commit/b9db586107db608b3116516af17ba71236fb2852#diff-a35d58c9e83bb9b71a960765acb237a434cd12041870f6edbf7f5331d7c7a7e7). @juruchi  to discuss with Goro how to proceed.

**Comment by juruchi** [comment]
Will op. mortality specific key-value pairs

**Comment by kam642** [comment]
@ran-codes @juruchi Is there anything still pending from me on this?
