### ISSUE TITLE
L2_5 + L3 Crosswalk

### ISSUE THREAD

**Issue by ran-codes** [Drexel-UHC/salurbal-fair-renovations#105]
**@kam642 can you help me find the official L3 + L2_5 crosswalks?**

I need them to make a table for the about page. see below.

> Insert figure or table here showing number of L1ADs, number L2 and number of L3s (using 2.5s in the cases where we have deemed that that is the appropriate neighborhood unit) by country.

I found the L1 and L2 here: \\files.drexel.edu\colleges\SOPH\Shared\UHC\Projects\Wellcome_Trust\Data Methods Core\Data\Admin_Boundary_Crosswalks but couldn't find a single L2_5/L3 one.

**Comment by kam642** [comment]
@ran-codes Due to size and difference by country, there is a different file for each country, not one master file.

@sjmelly Can you point @ran-codes to the L2.5/L3 crosswalks?

**Comment by sjmelly** [comment]
@ran-codes @kam642  I would use the tables in Appendix D of the City Selection Protocol. If these don't agree with the crosswalks we should update them. Keep in mind that the L2 crosswalks (and some L3 crosswalks) include records for L2s outside L1ADs that are associated with alternative metropolitan area definitions (SALID2 = missing). There's not a table for L2.5s in the city selection protocol but we created one somewhere. 
The L3/L2.5 crosswalks can be found in
\Projects\Wellcome_Trust\Data Methods Core\Data\Admin_Boundary_Crosswalks\
AR\arfc_salurbal_8_12_21.sas7bdat (2.5)
BR\brap_salurbal_6_9_21.sas7bdat (2.5)
CL\clzc2016_salurbal_12_3_20.sas7bdat (2016 is baseline year)
CO\co_salurbal_l3_10_29_21.sas7bdat
CR\crdto_salurbal_1_4_21.sas7bdat (2.5)
GT\gtsc_salurbal_11_13_20.sas7bdat
MX\mxageburb_salurbal_10_6_20.sas7bdat
NI – not available
PA\pacorbar_salurbal_10_7_20.sas7bdat
PE\pezo_salurbal_04_14_23.sas7bdat
SV\ we have a crosswalk but we never used L3s svsc_salurbal_11_11_19.sas7bdat

**Comment by ran-codes** [comment]
closing as summary done. commits tracked in duplicate issue:  https://github.com/Drexel-UHC/salurbal-project-dashboard/issues/336
