### ISSUE TITLE
Dataset Update - APS_v2.0

### ISSUE THREAD

**Issue by kam642** [Drexel-UHC/salurbal-fair-renovations#116]
Major update to APS (air pollution dataset) where the variables for NO2 are now from a new source. The NO2 data from the older source were renamed.

 ## Action Items 
  - [x] ETL setup
  - [x] define data-metadata relationships -> **linkage.csv**
  - [x] generate codebook templates -> **4.0-template__codebooks.xlsx**
  - [x] initial filling out of codebooks  -> **4.1-raw__codebooks.xlsx**
  - [x] QC of initial codebooks -> **4.2-base__codebooks.xlsx**
  - [ ] Review of base codebooks  -> **4.3-int__codebooks.xlsx**
  - [ ] QC of intermediate codebooks  -> **4.4-final__codebooks.xlsx**
  - [ ] Integration and loading into data warehouse

**Comment by ran-codes** [comment]
## Action Items

-  [ ] pending #118 update of renovation setup
-  [ ] make renovation_setup() robust to new versions. In this case init as a copy of most recent version but replace version_tmp. maybe just manually update with copy paste?

**Comment by ran-codes** [comment]
@kam642  The codebook is ready for your review. Details on codebook fields can be found [here in the sheet named 4-codebook.csv ](https://github.com/Drexel-UHC/salurbal-fair-renovations/raw/main/documents/templates/_template_details.xlsx) Let us know if you have any questions!

## Action items

- [ ] Review [4.2-base__codebook.xlsx](https://github.com/Drexel-UHC/salurbal-fair-renovations/files/12017652/4.2-base__codebook.xlsx)
- [ ] Make edits as needed and save in a file called **4.3-int__codebook.xlsx**
- [ ] Comment in this issue when the final version is ready and upload the file to this issue via drag and drop

**Comment by kam642** [comment]
@ran-codes The column names don't look right in the 4.2-base__codebook. Something seems off. Can you check this?

**Comment by ran-codes** [comment]
Sure, @kam642 anything sepcific I should look for?

**Comment by kam642** [comment]
@ran-codes It looks like quite a few of the columns are likely mislabeled. For example, all of the var_label are "Physical and Natural Environment"

**Comment by ran-codes** [comment]
ahh I see. 😨  Thanks for pointing that out. Will let you know when its fixed!

**Comment by ran-codes** [comment]
@kam642 Column shift bug was fixed. The codebook should now be ready for your review. Details on codebook fields can be found [here in the sheet named 4-codebook.csv ](https://github.com/Drexel-UHC/salurbal-fair-renovations/raw/main/documents/templates/_template_details.xlsx) Let us know if you have any questions!

## Action items

- [ ] Review Updated [4.2-base__codebook.xlsx](https://github.com/Drexel-UHC/salurbal-fair-renovations/files/12185068/4.2-base__codebook.xlsx)
- [ ] Make edits as needed and save in a file called **4.3-int__codebook.xlsx**
- [ ] Comment in this issue when the final version is ready and upload the file to this issue via drag and drop

**Comment by ran-codes** [comment]
@kam642 just a piece of feedback that is relevant from Caludio Kanai (see below). This was on the APS_v1.0 dataset soo I think these should be fixed in APS_v2.0. Can you address Claudio's comments briefly when reviewing APS_v2.0?


>In the Data Catalog, please review the metadata for air pollution variables, especially the NO2 variables. For Salurbal, we produced NO2 measurements from two sources: ATMOS and Anenberg et al. I noticed a mixing of information from both sources in the metadata. For example, the variable "Area-weighted NO2 average concentration" (APSNO2MEAN) is described as the "Weighted arithmetic mean of NO2 measurements for all grid cells with any part of the grid cell contained in the defined boundary weighted by the percent of the total area contained within the boundary (NO2 - Nitrogen Dioxide)". This description pertains to NO2 measurements produced based on ATMOS data (11km resolution), specifically the APSDNO2MEAN variable. However, there is a remark in the "Notes" section about the data version of PM2.5 satellite data, which appears unrelated. Additionally, the "data sources" tab lists years of available data that seem to be associated with the Anenberg data (NO2 resolution 1km). I suggest reviewing the air pollution metadata using the file "Codebook_APS_04072023" to ensure accurate information regarding the different variables of air pollution data, which can be found in the Salurbal Data Documentation.

**Comment by kam642** [comment]
@ran-codes Can you send me the renovated version of APS_v1.0 codebook? There are things like "units" in this version that aren't completed and it would be easier if I can copy from older version.

**Comment by kam642** [comment]
@ran-codes Done!

[4.3-int__codebook.xlsx](https://github.com/Drexel-UHC/salurbal-fair-renovations/files/12343929/4.3-int__codebook.xlsx)

**Comment by ran-codes** [comment]
thanks @kam642 ! Intermediate codebooks passed testing and final codebooks generated.

Thanks everyone 🍰
