### ISSUE TITLE
Renovation - TMPDAILY

### ISSUE THREAD

**Issue by kam642** [Drexel-UHC/salurbal-fair-renovations#117]
New dataset for renovation saved in \\files.drexel.edu\colleges\SOPH\Shared\UHC\Projects\Wellcome_Trust\Data Methods Core\Data\Temperature\Daily

Note: L1AD and L1UX are in the same dataset (L1AD_UX_96_15) and L2 is in a separate dataset (L2_96_15)

 ## Action Items 

https://github.com/Drexel-UHC/salurbal-fair-renovations/tree/main/datasets/TMPDAILY/v1.0

  - [x] ETL setup
  - [x] need codebooks @kam642 
  - [x] define data-metadata relationships -> **linkage.csv**
  - [x] generate codebook templates -> **4.0-template__codebooks.xlsx**
  - [x] initial filling out of codebooks  -> **4.1-raw__codebooks.xlsx**
  - [x] QC of initial codebooks -> **4.2-base__codebooks.xlsx**
  - [ ] Review of base codebooks  -> **4.3-int__codebooks.xlsx**
  - [ ] QC of intermediate codebooks  -> **4.4-final__codebooks.xlsx**
  - [ ] Integration and loading into data warehouse

**Comment by ran-codes** [comment]
## Action Items

- [ ] @ran-codes to update renovation_setup() func
- [ ] @ran-codes test on a branch 
- [ ] @juruchi to reproduce the setup on main 
- [ ] @juruchi to fill in all {brain} sections

**Comment by AnaPeraltaG** [comment]
@juruchi 

Hi Jess. The raw codebook is ready to review. There is missing information since there is no codebook for this dataset. Thanks!

**Comment by juruchi** [comment]
@kam642 The codebook is ready for review. Details on codebook fields can be found [here](https://github.com/Drexel-UHC/salurbal-fair-renovations/raw/main/documents/templates/_template_details.xlsx). Let us know if you have any questions!

## Action items
- [ ] Review codebook  [4.2-base__codebook.xlsx](https://github.com/Drexel-UHC/salurbal-fair-renovations/blob/main/datasets/TMPDAILY/v1.0/4.2-base__codebook.xlsx)
- [ ] Make edits as needed and save in a file called **4.3-int__codebook.xlsx**
- [ ] Comment in this issue when the final version is ready and upload the file to this issue via drag and drop

### Reminder
The codebook contains missing information since we were unable to locate variable documentation for the dataset

**Comment by kam642** [comment]
@juruchi This needs to go to BEC group for review. I think we added a couple of additional columns to the BEC codebook for them, correct? Can you add those columns to this and then I'll send to Olga Lucia and Daniel so they can assign to their team?

**Comment by juruchi** [comment]
Added source_URL and source_terms_of_use_URL columns. Please use the base_codebook link above to access the latest codebook.

**Comment by kam642** [comment]
Sent to Daniel and Olga Lucia to assign to BEC.

**Comment by juruchi** [comment]
Draft received from BEC team. Will look it over next week.

**Comment by juruchi** [comment]
@kam642 
## Action items
- [ ] Review the BEC team's codebook [4.3-int__codebook.xlsx](https://github.com/Drexel-UHC/salurbal-fair-renovations/blob/main/datasets/TMPDAILY/v1.0/4.3-int__codebook.xlsx)
- [ ] Make edits as needed and save in a file called **4.3-int__codebook_KM.xlsx**
- [ ] Comment in this issue when the final version is ready and upload the file to this issue via drag and drop

**Comment by kam642** [comment]
@juruchi I made some edits in the codebook attached here. There is one piece missing. For the population weighted estimates, we need to have the source for the population data that was used for the weighting. Can you check with whoever reviewed this codebook at BEC (Thomas, I think) to add this information?

[4.3-int__codebook.xlsx](https://github.com/Drexel-UHC/salurbal-fair-renovations/files/12648079/4.3-int__codebook.xlsx)

**Comment by juruchi** [comment]
Emailed Thomas for this info

**Comment by kam642** [comment]
@kam642 Will check with Josiah about what population data was used for the weights.

**Comment by kam642** [comment]
Question sent to Daniel and Josiah:

We’re reviewing all the data sources used for the temperature data to determine data use restrictions. Can you check that this is correct and answer my question about the population data used in weighting?

Temperature data is from ERA5-Land https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-land?tab=overview

For population weights, it looks like 2 sources were used. Is that correct?

For most countries (except PA and PE), WorldPop 2010 data was used: http://www.worldpop.org.uk/data/get_data/

For PA and PE, Global Urban footprint data was used? What is the link for the source of this population data? I can’t find that.


From document: “Daily mean temperature at the city and sub-city levels from 1996 to 2015, for L1AD, L1UX and L2 units. We provide area-weighted averages for each spatial unit as well as averages further weighted by population, using 100m x 100m WorldPop data for 2010. Since population data is not accurate for Panama and Peru, for cities in these two countries we weight temperature by urban footprint data (Global Urban Footprint)”

**Comment by kam642** [comment]
Response from Josiah:
“To better approximate population exposures, we spatially weighted city temperature using 2010 estimates of the spatial distribution of the population (WorldPop, [https://www.worldpop.org](https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.worldpop.org%2F&data=05%7C01%7Ckam642%40drexel.edu%7C104fce19fa324653278308dbc990b396%7C3664e6fa47bd45a696708c4f080f8ca6%7C0%7C0%7C638325395545701913%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=LXDOGN3l9OWH1DvQTkvqQ7jWFRXE41T89O65pG5s6yk%3D&reserved=0): Argentina, Brazil, Chile, Costa Rica, El Salvador, Guatemala and Mexico) or urban footprint (Global Urban Footprint, [https://www.un-spider.org/node/11424](https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.un-spider.org%2Fnode%2F11424&data=05%7C01%7Ckam642%40drexel.edu%7C104fce19fa324653278308dbc990b396%7C3664e6fa47bd45a696708c4f080f8ca6%7C0%7C0%7C638325395545701913%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=eI5T8HcgreDWJ7H1vSi1eapeLvNe6NyuD%2Bz043sTTuA%3D&reserved=0): Panama and Peru).”


@juruchi I think we need to change the codebook such that we have an src file that includes ERA5-land, world pop, and GUF pop. Then a source column needs to be added to the by_var.
Is it possible for you to generate with these updates and I can fill them out?

**Comment by kam642** [comment]
@juruchi @ran-codes Done!
I added tabs for src for the data sources for temperature (named the key temperature) and population (name the key populationBEC because this population data was used for other measures in the BEC dataset. Is this ok?)

I did send one more question to Josiah and Daniel about acknowledgement but I'm not expecting them to have the info so will likely just use what I have included in the attached file.
Email sent:
"According to WorldPop website FAQ, it says:
When downloading each dataset, a recommended citation is provided, as well as a doi for the dataset.

Would it be possible to send me the recommended citation and DOI that was provided with the dataset that was downloaded?"




[4.3-int__codebook_KM.xlsx](https://github.com/Drexel-UHC/salurbal-fair-renovations/files/12882587/4.3-int__codebook_KM.xlsx)

**Comment by kam642** [comment]
@juruchi @ran-codes Made an update based on Thomas's response to WorldPop citation. Use this version:



[4.3-int__codebook_KM.xlsx](https://github.com/Drexel-UHC/salurbal-fair-renovations/files/12893187/4.3-int__codebook_KM.xlsx)


Response from Thomas:
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/kam642/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/kam642/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/kam642/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US link=blue vlink="#954F72" style='tab-interval:.5in;word-wrap:
break-word'>




DOI | DOI Link | Description | Citation
-- | -- | -- | --
10.5258/SOTON/WP00651 | 10.5258/SOTON/WP00650 | The dataset is available to   download in Geotiff format at a resolution of 3 arc-second (approximately   100m at the equator). The projection is Geographic Coordinate System, WGS84.   Grid cell values represent International Standard 3-digit numerical ISO 3166   Country Codes corresponding to country and territory names as designated by   the United Nations (ISO, 2017). It is important to note that these data are   not official representations of country boundaries, some of which are   disputed, but simply represent the source of the population count data.   Data Source: Global national level input population data-summary   Methodology: Lloyd, C. T., H. Chamberlain, D. Kerr, G. Yetman, L. Pistolesi,   F. R. Stevens, A. E. Gaughan, J. J. Nieves, G. Hornby, K. MacManus, P. Sinha,   M. Bondarenko, A. Sorichetta, and A. J. Tatem, 2019. “Global   Spatio-temporally Harmonised Datasets for Producing High-resolution Gridded Population   Distribution Datasets”. Big Earth Data (https://doi.org/10.1080/20964471.2019.1625151).      Region : Colombia   DOI : 10.5258/SOTON/WP00651   Date of production : 2018-11-02 | WorldPop (www.worldpop.org - School of Geography and   Environmental Science, University of Southampton; Department of Geography and   Geosciences, University of Louisville; Departement de Geographie, Universite   de Namur) and Center for International Earth Science Information Network   (CIESIN), Columbia University (2018). Global High Resolution Population   Denominators Project - Funded by The Bill and Melinda Gates Foundation   (OPP1134076). https://dx.doi.org/10.5258/SOTON/WP00651



</google-sheets-html-origin>
</body>

</html>
DOI	DOI Link	Description	Citation
10.5258/SOTON/WP00651	10.5258/SOTON/WP00650	The dataset is available to download in Geotiff format at a resolution of 3 arc-second (approximately 100m at the equator). The projection is Geographic Coordinate System, WGS84. Grid cell values represent International Standard 3-digit numerical ISO 3166 Country Codes corresponding to country and territory names as designated by the United Nations (ISO, 2017). It is important to note that these data are not official representations of country boundaries, some of which are disputed, but simply represent the source of the population count data.
Data Source: Global national level input population data-summary
Methodology: Lloyd, C. T., H. Chamberlain, D. Kerr, G. Yetman, L. Pistolesi, F. R. Stevens, A. E. Gaughan, J. J. Nieves, G. Hornby, K. MacManus, P. Sinha, M. Bondarenko, A. Sorichetta, and A. J. Tatem, 2019. “Global Spatio-temporally Harmonised Datasets for Producing High-resolution Gridded Population Distribution Datasets”. Big Earth Data (https://doi.org/10.1080/20964471.2019.1625151).

Region : Colombia
DOI : 10.5258/SOTON/WP00651
Date of production : 2018-11-02	WorldPop ([www.worldpop.org](http://www.worldpop.org/) - School of Geography and Environmental Science, University of Southampton; Department of Geography and Geosciences, University of Louisville; Departement de Geographie, Universite de Namur) and Center for International Earth Science Information Network (CIESIN), Columbia University (2018). Global High Resolution Population Denominators Project - Funded by The Bill and Melinda Gates Foundation (OPP1134076). [https://dx.doi.org/10.5258/SOTON/WP00651](https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdx.doi.org%2F10.5258%2FSOTON%2FWP00651&data=05%7C01%7Ckam642%40drexel.edu%7C7e8381c367f74801270308dbcb6e7385%7C3664e6fa47bd45a696708c4f080f8ca6%7C0%7C0%7C638327447475391224%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0JV65gN7%2BKX76kX%2FdoZRn8FfSht4VyXkTzw1okqoa%2F4%3D&reserved=0)

**Comment by juruchi** [comment]
@kam642 A few questions: 

1. The link [https://codes.ecmwf.int/grib/param-db/?id=167](https://codes.ecmwf.int/grib/param-db/?id=167) appears by itself in cell B3 under the dataset_notes column in the by_dataset sheet. Should this link be incorporated into the notes in cell B2 or can it be deleted?
2. There are no listed codebook files under the file_codebook column in the by_dataset sheet. Is this column meant to be empty?
3. The acknowledgement for tmp_pw only includes the acknowledgement for {{temperature}}. Should the acknowledgement for {{populationBEC}} be listed as well?
4. Acknowledgements and public values have been manually entered for both tmp variables. Should these be replaced with the values entered for source?

**Comment by kam642** [comment]
@juruchi 
i. The link https://codes.ecmwf.int/grib/param-db/?id=167 appears by itself in cell B3 under the dataset_notes column in the by_dataset sheet. Should this link be incorporated into the notes in cell B2 or can it be deleted?

-Can you add this to the cell B2 above?


ii. There are no listed codebook files under the file_codebook column in the by_dataset sheet. Is this column meant to be empty?

-We never received a codebook for this dataset from BEC. I think we can leave this empty.


iii. The acknowledgement for tmp_pw only includes the acknowledgement for {{temperature}}. Should the acknowledgement for {{populationBEC}} be listed as well?

-Yes! Oversight on my part. Thanks for catching that.


iv. Acknowledgements and public values have been manually entered for both tmp variables. Should these be replaced with the values entered for source?

-Yes. I always get confused on when to enter for source vs. variable.

**Comment by juruchi** [comment]
@ran-codes I've created population-BEC and temperature src files to be used in this dataset's codebook. When I run ```_src.R```, I get the error ```✖ by_key_iso2 has invalid seperators! Please check!```. The population acknowledgement_value uses semicolons to separate different sources, which I believe is causing the error. What is the reasoning behind having ';' as an invalid separator? (Maybe I'm missunderstanding the validation test?) Can we remove or somehow change the ```valid_no_seperator``` test?

**Comment by ran-codes** [comment]
taking a look now

**Comment by ran-codes** [comment]
i've quarentined it for now. (might have unintended consequences but we'll deal with it eventually ... also we probably need a more robust/unique seperator rather than `;`  Can you take a look at #186 and provide suggestions. Thanks!


(Just heads up all compile_jinja() functions have just been upgraded to handle dynamic linkages  so there still may be bugs... if you run into them just report on the dataset issue and we'll smooth it out). Thanks for your understanding!!

**Comment by ran-codes** [comment]
Thanks for the updates @juruchi and clarifications @kam642.

renovation function updated for new compile functions then final processing as done. THanks all!
