### ISSUE TITLE
Dataset Renovation - MR_allcause_v1.0

### ISSUE THREAD

**Issue by juruchi** [Drexel-UHC/salurbal-fair-renovations#118]
\\files.drexel.edu\colleges\SOPH\Shared\UHC\Projects\Wellcome_Trust\Data Methods Core\Data\Mortality Data\Mortality Rate

 ## Action Items 
  - [x] ETL setup
  - [x] define data-metadata relationships -> **linkage.csv**
  - [x] generate codebook templates -> **4.0-template__codebooks.xlsx**
  - [x] initial filling out of codebooks  -> **4.1-raw__codebooks.xlsx**
  - [x] QC of initial codebooks -> **4.2-base__codebooks.xlsx**
  - [x] Review of base codebooks  -> **4.3-int__codebooks.xlsx**
  - [x] QC of intermediate codebooks  -> **4.4-final__codebooks.xlsx**
  - [x] Integration and loading into data warehouse

**Comment by juruchi** [comment]
Good question. @goro-yamada I can't remember if we discussed this. Should all the mortality rate data be public or should public be the same as one of the source variables (mortality: vital registration or population count: population)?

**Comment by goro-yamada** [comment]
It should follow the union of vital registration and population. I.e., Argentina, Costa Rica, and Panama should not be available to the public as of now. We do not have their clearance yet.

**Comment by ran-codes** [comment]
# Scenarios for compile_public_jinja()

### Raw
```md
{{population}};{{vital-registration}}
```

### Base
```
{population} 1; {vital-registration} 1
{population} 1; {vital-registration} 0
{population} 1; {vital-registration} 9
```

### Final
```
1
0
9
```


# Action Items

- [ ] @juruchi udpate compile_public_jinja() to accomodate 2+ keys
- [ ] run through 
- [ ] send to goro

**Comment by ran-codes** [comment]
@juruchi PR merged see notes in #135. If base_codebooks look good to you feel free to send to Goro for review. thanks again !!

**Comment by juruchi** [comment]
@ran-codes How can I update i$src to reflect the current source inventory? The base codebooks do not reflect the public changes for panama and costa rica #136 #138

**Comment by ran-codes** [comment]
sorry about that. it was a typo in  get_etl_imports() that was pointing towards a older directory. pull and refresh project and it should work!

**Comment by juruchi** [comment]
@goro-yamada The codebook is ready for your review. Details on codebook fields can be found [here](https://github.com/Drexel-UHC/salurbal-fair-renovations/raw/main/documents/templates/_template_details.xlsx). Let us know if you have any questions!

## Action items
- [ ] Review [associated sources for {{population}} ](https://github.com/Drexel-UHC/salurbal-fair-renovations/blob/main/datasets/_src/src__population.xlsx)
- [ ] Review [associated sources for {{vital-registration}} ](https://github.com/Drexel-UHC/salurbal-fair-renovations/blob/main/datasets/_src/src__vital_registration.xlsx)
- [ ] Make edits as needed and save in a file called **src__population-GY.xlsx / src__vital_registration-GY.xlsx**
- [ ] Review codebook  [4.2-base__codebook.xlsx](https://github.com/Drexel-UHC/salurbal-fair-renovations/blob/main/datasets/MR_allcause/v1.0/4.2-base__codebook.xlsx)
- [ ] Make edits as needed and save in a file called **4.3-int__codebook.xlsx**
- [ ] Comment in this issue when the final version is ready and upload the file to this issue via drag and drop

### Notes
For the final public values we plan on using the following logic.
1. If either population or vital registration is 0 the final public value will be 0
2. If either population or vital registration is 9 the final public value will be 9
3. If both population and vital registration values are set to 1 the final public value will be 1

**Comment by goro-yamada** [comment]
I will review the codebooks, but the logic above seems complicated since they are not mutually exclusive. For example, what will be the final value if one data is 0 and the other is 9? An alternative could be:
1. If both population and vital registration values are set to 1, the final public value will be 1; otherwise (go to the following condition)
2. If either dataset is 0, the final is 0; otherwise, 9.

**Comment by ran-codes** [comment]
@goro-yamada good point.

The status quo is set up so that the final codebook will have that logic compiled into a single value. The intermediate codebook you are reviewing is meant to keep that original source and values as indicated by `{key} value` for you to understand that these are compiled from a master dictionary and for your to do a review. There is a downstream step that will determine the final value using `or` logic.

If this is not helpful then we can just compile into the final value for the intermediate codebook for you to review 0 or 9 in this case. Let us know what works best.

**Comment by ran-codes** [comment]
Thanks for your patience goro. Sorry for not being clear.  But i understand what you are saying at least = ).

Our codebook has different steps and by the final step the logic will be complete. An example of the lifecycle can be shown below. You are reviewing the base codebook; if nothing changes then logic will be completed in final codebook where it it is entered into a database. 

### Raw
```md
{{population}};{{vital-registration}}
```

### Base  
```
{population} 1; {vital-registration} 1
{population} 1; {vital-registration} 0
{population} 1; {vital-registration} 9
```

### Final
```
1
0
9
```

**Comment by goro-yamada** [comment]
@juruchi 
In src__population, but not src__vital_registration, I noticed that the institution name of Panama was incorrect (“… y Censo”, not “… y Censos”). You would need to correct the master file(s). FYI, the following institution names are very similar, which may cause errors.
- Instituto Nacional de Estadística y Censos (INEC), Costa Rica
- Instituto Nacional de Estadística y Censo (INEC), Panama

src__vital_registration: The explanation of the confidence interval was confusing and strange. Also, this is about 95% CI, not 99% or 90%, so it should be stated. 

[src__population-GY.xlsx](https://github.com/Drexel-UHC/salurbal-fair-renovations/files/12113166/src__population-GY.xlsx)
[src__vital_registration-GY.xlsx](https://github.com/Drexel-UHC/salurbal-fair-renovations/files/12113167/src__vital_registration-GY.xlsx)
[4.3-int__codebook.xlsx](https://github.com/Drexel-UHC/salurbal-fair-renovations/files/12113178/4.3-int__codebook.xlsx)

**Comment by juruchi** [comment]
@goro-yamada Just to confirm, there were no changes to the src__vital_registration?

**Comment by goro-yamada** [comment]
No changes. It was good.

**Comment by juruchi** [comment]
@ran-codes There are changes to confidence interval variable definitions in the int codebook. I was thinking of removing the compilation for the LCI and UCI to keep the new definitions, but I know there was a conversation about generic LCI/UCI language #101. Should I go ahead and remove the compilation or is there a different approach that we can take?

**Comment by juruchi** [comment]
Reopening issue. Will suppress crude mortality rate for AR.
