### ISSUE TITLE
Only include latest year of data

### ISSUE THREAD

**Issue by kam642** [Drexel-UHC/salurbal-fair-renovations#119]
For the June 28 release, we do not want to include any longitudinal data. For all data that will be released, only include the latest year available. We do not want to release data that is being used by currently in progress high priority manuscripts.

**Comment by ran-codes** [comment]
## Action Items

- [ ] public export only single year
- [ ] front end: remove  year selection from checkout

**Comment by ran-codes** [comment]
closing. all publicly downlaodable data have been limited to most recent year for all combinations of primary keys.
