### ISSUE TITLE
Variable list to review for pre-release

### ISSUE THREAD

**Issue by ran-codes** [Drexel-UHC/salurbal-fair-renovations#124]
@kam642 you can review the [variable level inventory](https://github.com/Drexel-UHC/salurbal-fair-renovations/files/11821899/variables.csv) for the data portal. Note the field you are interested are interested in is `partial_public` this is a variable level summary of `public`. it has a value of **1** if any year/iso2 for this variable has public == 1.

**Comment by kam642** [comment]
@ran-codes Attached here. I added a column "keep" where 1 indicates we can release on Jun 28 (latest year of data only - not longitudinal data). There are a few that are marked as keep=1 but partial_public=0. For these, they can be added as soon as the renovation is completed but may not be ready by Jun 28.


[variables.csv](https://github.com/Drexel-UHC/salurbal-fair-renovations/files/11848527/variables.csv)

**Comment by ran-codes** [comment]
Thanks @kam642! These censorship rules have been implemented. 

The only data points that are public accessible are those that are legally accessible (public == 1) as well as uncorsored (keep == 1).
