### ISSUE TITLE
ETL Spatial data and metadata for Data Portal

### ISSUE THREAD

**Issue by ran-codes** [Drexel-UHC/salurbal-fair-renovations#153]
# Action Item

- [x] @ran-codes to send public crosswalks to @sjmelly 
- [x] @sjmelly to create
  - [x] internal version with (said)
  - [x] public versions (with public id)
  - [x] send excel invotory
  - [x] create .shp + .gdb
- [x]  @ran-codes ETL
   - [x] inventory ` \Projects\Wellcome_Trust\Data Methods Core\Geodatabases\SALURBAL_4_10_23\forSALURBALPortal`
   - [x] upload endpoint files to storage (DSWG public repo for now)
      - [x] .gdb
      - [x] .shp
   - [x] import layer metadata
   - [x] op. layer metadata as json
   - [x] implement front end (https://github.com/Drexel-UHC/salurbal-project-dashboard/issues/387)

### Metadata page example
![image](https://github.com/Drexel-UHC/salurbal-fair-renovations/assets/45013044/4ac40ff9-17fc-4f4f-bccf-61804cbd9fac)

**Comment by ran-codes** [comment]
@sjmelly all the salid-public crosswalks can be found here: \\files.drexel.edu\colleges\SOPH\Shared\UHC\Projects\Wellcome_Trust\Data Methods Core\Dashboards\FAIR Renovations\_crosswalks

Note we will regenerate these with update names and such after we get your renovated .GDB files so don't worry about inconsistencies for now. All metadata will come from the GDB you send.

**Comment by sjmelly** [comment]
Thanks @ran-codes  @Nat325 see location for salid public crosswalks

**Comment by sjmelly** [comment]
@ran-codes @Nat325 we have saved an example of metadata as .xml file to \Projects\Wellcome_Trust\Data Methods Core\Geodatabases\SALURBAL_4_10_23\forSALURBALPortal  
In a .rtf version, I highlighted the sections that we have currently been completing. 
We have been working on updating UHC's protocol for data management. I have attached proposed text about spatial data metadata
[SpatialDataMetadataUHCPractices20230824.docx](https://github.com/Drexel-UHC/salurbal-fair-renovations/files/12430999/SpatialDataMetadataUHCPractices20230824.docx)

**Comment by sjmelly** [comment]
@ran-codes We have been translating this discussion into tasks in the project SALURBAL1 Spatial Data Inventory in the SALURBAL DMC repository

**Comment by sjmelly** [comment]
@ran-codes @kam642 Are you planning to use id0, id1, id2 as variable names for the public IDs? This potentially creates confusion with GADM data which use ID_0 (Country); ID_1 (first administrative level e.g. state); ID_2 (second administrative level e.g. departamento)
> @sjmelly all the salid-public crosswalks can be found here: `\\files.drexel.edu\colleges\SOPH\Shared\UHC\Projects\Wellcome_Trust\Data Methods Core\Dashboards\FAIR Renovations\_crosswalks`
> 
> Note we will regenerate these with update names and such after we get your renovated .GDB files so don't worry about inconsistencies for now. All metadata will come from the GDB you send.

**Comment by ran-codes** [comment]
we can rename them to public_salid0, public_salid1 .... etc if needed. lmk what works best.

**Comment by ran-codes** [comment]
> I would vote for something shorter e.g. pubsalid1 or pbsalid1.

I like `pubsalid#`!!! 👍 

--- 

> Did we decide that L1 label and L2 label should include diacritical marks and be in the language of the country 

I forgot the decision Steve. But i think best be safe have have **both operationalized**. so maybe `l1_name_diacritical` and `l1_name`(which is just the non-diacritical/full-english version).

--- 

>Is replacing spaces with hyphens a standard practice (as in l1_name and L2_name)? Should we start doing this in our spatial datasets?

Yes, please replace spaces with underdashes! in general it is easier to work with if spaces are replaced with undersdashes. `L1 Name` 😢  vs `l1_name` 😄. This is probably a whole discussion but my 2 cents:

-  makes it easier to work with most databases. without spaces you often have to wrap the column name  with enclosing syntax so queries are a little more complex
- also interoperability withdifferent environments (R, Python, SAS ) where its mostly recommended not to include spaces in column names.

**Comment by sjmelly** [comment]
I didn't mean spaces in variable/column names or file names. I meant spaces in the city names themselves. This gets confusing when we have L1s made up of more than one city san-miguel-de-tucuman-tafi-viejo
In some cases there are three hyphens between the city names rawson---trelew

**Comment by ran-codes** [comment]
o i see. In terms of City names, spaces are good! I think the way you have it formated is perfect! (for context, the hyphenated ones are just operationalized from the original city names for use in case we need to generate URLs for each city for example https://data.lacurbanhealth.org/city-profile/san-cristobal-de-las-casas)

**Comment by ran-codes** [comment]
@sjmelly i remember you shared with a excel sheet during a zoom meeting that described each geo-database in `\Projects\Wellcome_Trust\Data Methods Core\Geodatabases\SALURBAL_4_10_23\forSALURBALPortal`. Can share that again. Thanks!

**Comment by sjmelly** [comment]
You will want the BaselineTopologyCorrected worksheet and can filter on SALURBAL Portal = X
We are saving the Excel file in \Projects\Wellcome_Trust\Data Methods Core\Geodatabases\SALURBAL_4_10_23\ SALURBALSpatialData20230512.xlsx
[SALURBALSpatialData20230512.xlsx](https://github.com/Drexel-UHC/salurbal-fair-renovations/files/12479850/SALURBALSpatialData20230512.xlsx)
These files include Country SALID is that OK?

**Comment by ran-codes** [comment]
Thanks Steve!! (Its fine they include SALID. I can remove them or do linkages if needed). Will keep you updated!

**Comment by sjmelly** [comment]
The public files just have the country level SALID; L1 and L2 level IDs are PUBSALID

**Comment by ran-codes** [comment]
Note for future: resrouces for working with XML in R

- https://appsilon.com/r-xml/

**Comment by ran-codes** [comment]
@sjmelly would it be possible for these public facing layers and .gdb to make their arcgis online content  (or at least the map) public facing? (so people can view without logging in or we can embed into other websites?)

**Comment by sjmelly** [comment]
ESRI is blurring the distinction between geodatabase feature classes saved on local computers and web layers from ArcGIS online. Both can be added to ArcGISPro projects, but not all ArcGISPro tools will work with web layers. Because the metadata for the web layers came from the file geodatabase feature class the web layer metadata says type = file geodatabase feature class. I think the user needs to look at the properties of the layer to determine the actual type
Web layer properties:
![image](https://github.com/Drexel-UHC/salurbal-fair-renovations/assets/16820816/3a4550ff-1f5f-4273-98be-ae9aeabd3d44)
Feature class properties:
![image](https://github.com/Drexel-UHC/salurbal-fair-renovations/assets/16820816/ffe21ad1-f9d9-450b-bfcf-bfa48df73a60)

**Comment by ran-codes** [comment]
closing as initial pass at ArcGIS metadta processing is done and JSON data store items generated

**Comment by ran-codes** [comment]
## Action Items

- [ ] update as per #162 
- [ ] Op. API endpoints
   - [ ] standardize naming and store as 'processed'
   - [ ]  create public facing zipped as per API endpoints
   - [ ] write over to public API

**Comment by sjmelly** [comment]
@ran-codes I made a simple WebApp version of the ArcGIS online map with the L1 and L2 boundaries. https://drx.maps.arcgis.com/apps/instant/basic/index.html?appid=025fb2ad97394ac492c8ce6ddc1f0df1

Here's the information from ESRI about embedding the map:
<iframe src="https://drx.maps.arcgis.com/apps/instant/basic/index.html?appid=025fb2ad97394ac492c8ce6ddc1f0df1" width="400" height="600" frameborder="0" style="border:0" allowfullscreen>iFrames are not supported on this page.</iframe>

**Comment by ran-codes** [comment]
API generation done + updated with 9/15 metadata. closing
