### ISSUE TITLE
Dataset Renovation - ATUS_evento_1997_2019

### ISSUE THREAD

**Issue by kam642** [Drexel-UHC/salurbal-fair-renovations#161]
Need renovation for dataset ATUS_evento_1997_2019_06282022.csv (event level collision data). Codebook is \\files.drexel.edu\colleges\SOPH\Shared\UHC\Projects\Wellcome_Trust\Data Methods Core\Data\Police Data\Codebook_Police collisions collision level_06282022.xlsx. 
Document file is \\files.drexel.edu\colleges\SOPH\Shared\UHC\Projects\Wellcome_Trust\Data Methods Core\Data Documentation\Protocol Documents\Police Data\SALURBAL Police collisions Documentation_2022_07_01.docx

**Comment by juruchi** [comment]
Duplicated dataset. Removing this issue.
