### ISSUE TITLE
Spatial Renovation metadata issues

### ISSUE THREAD

**Issue by ran-codes** [Drexel-UHC/salurbal-fair-renovations#162]
@sjmelly I noteiced a few things that may need updating in the spatial metadata XML files, For several .GDB the `summary` and `description` don't seem correct?

- summaries does match with name
- the description does not match with name
 
# Table of name, summary, label 

![image](https://github.com/Drexel-UHC/salurbal-fair-renovations/assets/45013044/467b52d5-084b-45da-8071-e13a5cbbccb2)

# How it looks on ArcGIS

![image](https://user-images.githubusercontent.com/45013044/261099933-4ac40ff9-17fc-4f4f-bccf-61804cbd9fac.png)

**Comment by sjmelly** [comment]
@ran-codes I replaced the files in \Projects\Wellcome_Trust\Data Methods Core\Geodatabases\SALURBAL_4_10_23\forSALURBALPortal with files with today's date in the filename with updated metadata.

**Comment by ran-codes** [comment]
update done. Thanks for your help Steve.

I think for the future it would be great if you could write a protocol for generating these XML from ESRI. LMK what you think.

Maybe start out as a word doc, then we can add to a Quarto site somewhere or even just a GitHub discussion. I think standardizing and streamling spatial metadata would be great!

**Comment by ran-codes** [comment]
thanks @sjmelly. copied this over to discussions #164 for future reference.
