### ISSUE TITLE
Data Renovation - SEC_MIGRATION_v1.0

### ISSUE THREAD

**Issue by ran-codes** [Drexel-UHC/salurbal-fair-renovations#18]
https://github.com/Drexel-UHC/salurbal-fair-renovations/tree/main/datasets/SEC_MIGRATION

 ## Action Items 
  - [x] ETL setup
  - [x] define data-metadata relationships -> **linkage.csv**
  - [x] generate codebook templates -> **4.0-template__codebooks.xlsx**
  - [x] initial filling out of codebooks  -> **4.1-raw__codebooks.xlsx** @AnaPeraltaG 
  - [x] QC of initial codebooks -> **4.2-base__codebooks.xlsx**
  - [ ] Review of base codebooks  -> **4.3-int__codebooks.xlsx**
  - [ ] QC of intermediate codebooks  -> **4.4-final__codebooks.xlsx**
  - [ ] Integration and loading into data warehouse 

## Backlog
- [ ] Need primary metadata from SEC_Census

**Comment by AnaPeraltaG** [comment]
Hi @ran-codes. Just uploaded raw__linkage for this dataset. Thanks!

**Comment by ran-codes** [comment]
Thanks @AnaPeraltaG! templates have been generate. please pull 😆 and find them in the intermediate folder for this dataset `datasets/SEC_MIGRATION/intermediate/0-template__codebook.xslx`

please fill out and submit as `1-raw__codebook.xslx`

Thanks!

**Comment by AnaPeraltaG** [comment]
Hi @ran-codes! Raw__codebook for this dataset is ready to review, i just uploaded it. Thanks!

**Comment by ran-codes** [comment]
thanks @AnaPeraltaG!!

**Comment by juruchi** [comment]
@kam642 For SEC datasets is it okay to give a general description of where data came from for 'source'? Ex. "using census data for each country where questions to create these measures were available...REDATAM...For more information about the census data sources, see the SALURBAL Census Protocol."

Would it be more appropriate for 'source' info to be more specific and listed by country?

**Comment by kam642** [comment]
@juruchi I think it's more accurate to include the source for each country. It's still unclear to me where the protocols would be for someone using the public data. For someone downloading the data, it would be better to have all sources linked directly to the data.

**Comment by juruchi** [comment]
@kam642 For countries with multiple years of data do you prefer source to be listed by country or country and year?

**Comment by kam642** [comment]
@juruchi Can we do country and year? How does that look on the website for users?

**Comment by juruchi** [comment]
@ran-codes How does listing by country vs country & year affect users?

**Comment by ran-codes** [comment]
the useres see what we have availble in codebooks. if we just have sources by country then all countries will have the same source. if we have source by country/year then the sources will be resolvable by country/year. 

Hope that answers the question. 

At a functional level **for general users, I don't think country vs country/year sources matter too much.** As long as people have a sense of where the data is coming from I think most people will be happy. 

**But from an internal perspective it may be more important**.  Just ensuring data integrity and reproducibility it is important that we be able to track exactly where data came from... down to the exact raw data file (e.g. country and year)..

**Comment by AnaPeraltaG** [comment]
Hi @ran-codes @juruchi 

I have a question regarding the last tab (by_var_iso2_year) from the new template. There is a column to specify the source of each variable by country and year. The information is available in SALURBAL_SEC_Census Measures Protocol; however, I remember having to fill in a similar codebook before and we said we were going to create a census/population _source table to use as reference (See #21). Are we still doing that? I noticed that most of the codebooks I'm working on right now used census data, so I might need to have the source information by country and year in all those codebooks too. Thanks!

**Comment by AnaPeraltaG** [comment]
Ok. thanks!

It this what you mean by a document structured similar to a by_iso2_year? 

![Image](https://user-images.githubusercontent.com/115106613/236920639-24f0e246-eb00-4e21-aa2c-a2bcaeb6c943.png)

**Comment by ran-codes** [comment]
yup yup perfect! Thanks!! (just wanted to validate our existing list of sources) it looks good. 😄

**Comment by AnaPeraltaG** [comment]
@ran-codes 

The column _longitudinal_, is in by_var tab. Is it ok for me to write "yes" in the longitudinal column even though there is no data to conduct longitudinal analysis for all countries? (CNSMIGRFORBORN, for example. BR has data from 2010 only but CL has data from 2002 and 2017).

**Comment by ran-codes** [comment]
thoughts @kam642 ?

**Comment by kam642** [comment]
@AnaPeraltaG @ran-codes I think we should have "yes" in longitudinal if there is at least one country that has more than one year of data available.

**Comment by AnaPeraltaG** [comment]
@ran-codes a couple of things:

- I uploaded to Github the codebook for this dataset last night (using the previous template) but forgot to let you know by commenting this issue. I'll modify the codebook using 4.0-template__codebook.xlsx and will drop it here as requested :)
- What information should go into variable_origin ?

**Comment by ran-codes** [comment]
Thanks @AnaPeraltaG 

we'll talk about `variable_origin` at tomorrows meeting = )

**Comment by AnaPeraltaG** [comment]
Ok! Thanks!

Should I add  _source in 4.1-raw__codebooks.xlsx?

**Comment by AnaPeraltaG** [comment]
Hi @kam642. 

I'm working on the data sources for SECMIGRATION and noticed that there is data for MX corresponding to 2010 and 2015. However, SEC_census measures protocol describes that MX data from INEGI is available for the years 2000, 2010 and 2020. Is the data source for 2015 data still INEGI? Thanks

**Comment by kam642** [comment]
@ran-codes created the measures! @ran-codes Can you confirm the data source for 2015?

**Comment by ran-codes** [comment]
I just cleaned the files I got haha not sure where they came from. (I assume the same source as all other years which is INEGI?). @usamabilal can you confirm where the MX 2015 migration census data came from?

**Comment by usamabilal** [comment]
Inegi. Source is the census or Intercensal survey depending on year (same as al CNS)
________________________________

**Comment by ran-codes** [comment]
@kam642  The codebook is ready for your review. Details on codebook fields can be found [here](https://github.com/Drexel-UHC/salurbal-fair-renovations/raw/main/documents/templates/_template_details.xlsx) Let us know if you have any questions!

## Action items


- [ ] Review [4.2-base__codebook.xlsx](https://github.com/Drexel-UHC/salurbal-fair-renovations/files/11455986/4.2-base__codebook.xlsx)
- [ ] Make edits as needed and save in a file called **4.3-int__codebook.xlsx**
- [ ] Comment in this issue when the final version is ready and upload the file to this issue via drag and drop

**Comment by kam642** [comment]
@ran-codes @juruchi Done!
Check the public against the sources from the census (CNS/SEC_Census) data.

[4.3-int__codebook.xlsx](https://github.com/Drexel-UHC/salurbal-fair-renovations/files/11489009/4.3-int__codebook.xlsx)

**Comment by ran-codes** [comment]
Thanks everyone 🍰

looks great. integration done. closing this issue.
