### ISSUE TITLE
Dataset Renovation - UCNT_Longit_v1.0

### ISSUE THREAD

**Issue by juruchi** [Drexel-UHC/salurbal-fair-renovations#192]
Folder: https://github.com/Drexel-UHC/salurbal-fair-renovations/tree/main/datasets/UCNT_Longit

## Action Items 

  - [x] ETL setup
  - [x] define data-metadata relationships -> **linkage.csv**
  - [x] generate codebook templates -> **4.0-template__codebooks.xlsx**
  - [x] initial filling out of codebooks  -> **4.1-raw__codebooks.xlsx**
  - [x] QC of initial codebooks -> **4.2-base__codebooks.xlsx**
  - [x] Review of base codebooks  -> **4.3-int__codebooks.xlsx**
  - [x] QC of intermediate codebooks  -> **4.4-final__codebooks.xlsx**
  - [ ] Integration and loading into data warehouse

**Comment by juruchi** [comment]
@goro-yamada The codebook is ready for your review. Details on codebook fields can be found [here](https://github.com/Drexel-UHC/salurbal-fair-renovations/raw/main/documents/templates/_template_details.xlsx). Let us know if you have any questions!

## Action items
- [ ] Review codebook  [4.2-base__codebook.xlsx](https://github.com/Drexel-UHC/salurbal-fair-renovations/blob/main/datasets/UCNT_Longit/v1.0/4.2-base__codebook.xlsx)
- [ ] Make edits as needed and save in a file called **4.3-int__codebook.xlsx**
- [ ] Comment in this issue when the final version is ready and upload the file to this issue via drag and drop

Note that the dataset note included in this codebook will also be included in the mortality dataset codebooks (in addition to mentioning that the mortality count data has not been corrected for lack of complete coverage of death counts).

**Comment by goro-yamada** [comment]
@juruchi 
I edited the description of the dataset (the first sheet) a little bit. Apart from that, I did not modify anything!
[4.2-int__codebook.xlsx](https://github.com/Drexel-UHC/salurbal-fair-renovations/files/13301585/4.2-int__codebook.xlsx)

**Comment by goro-yamada** [comment]
@juruchi 
Oops, I saved it with 4.2-... instead of 4.3-.... Just in case, I am uploading the corrected one.
[4.3-int__codebook.xlsx](https://github.com/Drexel-UHC/salurbal-fair-renovations/files/13301604/4.3-int__codebook.xlsx)

**Comment by juruchi** [comment]
@ran-codes  ```etl_export_step6``` is generating the following error:
```! Subseting df_data to 10,000 rows for QC!
ℹ Step 6 (Denormalization)
! Denormalizing with PROTOTYPE metadata
Joining with `by = join_by(file_data, var_name)`
✔ Valid denormalization!                                                                                                                                           
Error in vctrs_vec_compat(.x, .purrr_user_env) : 
  object 'prod__codebooks' not found
```

The error originates from the ```Append 'public' to df_data (simple)``` chunk. I'm not really sure why prod_codebooks doesn't exist. Could you take a look?

**Comment by ran-codes** [comment]
yup taking a look now

**Comment by ran-codes** [comment]
fixed. it was small issue with get_etl_status() after some updates. Pull refresh nd try again?

**Comment by ran-codes** [comment]
BTW. (i think this si your first by your set up). So great job setting it up 😄

**Comment by juruchi** [comment]
Works now, thanks!

**Comment by juruchi** [comment]
Thanks everyone. Closing this issue.
