### ISSUE TITLE
Pop and vital registration updates before release 

### ISSUE THREAD

**Issue by ran-codes** [Drexel-UHC/salurbal-fair-renovations#194]
>There have been updates to the mortality and population datasets (addition of new years, updates to existing years). I want to make sure that the mortality, population, and undercounting datasets are all in sync. What is the best way to do this? Update the date for the data that is pulled in? Create a v2.0 folder depending on what datasets have new data? In relation to this, I see that within the population folder on the non-encrypted server, there is a renovation folder. Is there a script that pulls from each of the population subfolders to populate the renovation folder? 

### Action Items

- [x] @juruchi renovate 🚀  
   - [x] Mortality 
      - [x] #202 
      - [x] #203 
      - [x] #204 
      - [x] #206 
   - [x] Population 
      - [x] #198 
      - [x] #199 
      - [x] #200 
   - [x] Undercounting 
      - [x] #201 
- [ ] @ran-codes 
    - [x] add openxlsx and xlsx to dependencies or namescope the function calls
    - [ ] check `acknowledgemnet` compile bug
       - [ ] #206 
    - [ ] production run

**Comment by usamabilal** [comment]
We also need to renovate UCNT, right @juruchi ?

**Comment by juruchi** [comment]
Yes, just finishing that renovation now.

**Comment by usamabilal** [comment]
fantastic! now i wonder how do we deal with "cyclic" dependencies?
DTH (uncorrected) and PRJ -> UCNT -> DTH (corrected)

**Comment by juruchi** [comment]
Yes, that is what I'm also wondering about. 

This week we've updated mortality and population files and are finishing up quality checks on those. I'm hoping all the updates are moved out of the to_be_verified folders on Monday, so that it's easy to get the pop, mort, and ucnt files synced for the portal.

**Comment by ran-codes** [comment]
## Re: cyclic dependencies   

good question. I think one thing we could do is clearly define which datasets have a dependencies; for example mortality data sets, population dataset and undercounting datasets must all be computable with each other. So for the most downstream one that is v1.1 the upstream ones must at v1.1 must also be available. 

## Re: Jess' questions

### What is the best way to do this? Update the date for the data that is pulled in? Create a v2.0 folder depending on what datasets have new data?**
Yes I think you approach is correct. For example for UNCT. 

- You can view the snapshoted files for v1.0 here: `\\files.drexel.edu\colleges\SOPH\Shared\UHC\Projects\Wellcome_Trust\Data Methods Core\Data\Mortality Data\UCNT\_etl\UCNT_Longit_v1.0` 
- In the UCNT folder move that 'out of data' v1.0 files to archive and upload your new files (as you said with updated dates, so our import function detects this).
- Initialize a renovation func etl_UNCT_v2.0 function and process

then repeat for all the dataset within this family of datasets (UCNT, PRJ, DTH ... etc).



### **In relation to this, I see that within the population folder on the non-encrypted server, there is a renovation folder. Is there a script that pulls from each of the population subfolders to populate the renovation folder?**

If you mean `\\files.drexel.edu\colleges\SOPH\Shared\UHC\Projects\Wellcome_Trust\Data Methods Core\Dashboards\FAIR Renovations`. Don't worry about that folder it was a legacy folder used earlier one to test out codebooks but we are not using it anymore; as all codebooks and meetadta are just under version control in our GitHub repo

**Comment by juruchi** [comment]
All relevant files should be out of the to-be-verified later this morning. All pop (PRJ, PRJG, PRJS, PRJT), mortality (DTH, DTHRED1, DTHRED2, MR), and ucnt codebooks will needs to be updated. I will start with getting the vital-registration and population _src files updated. Once that's done, I'll start with initializing v2.0 for population, then move to mortality, and finally undercounting.

**Comment by ran-codes** [comment]
Thanks for the update and congrats on all the updates @juruchi. I will be on call to support as needed the next few days so feel free to assign me  datasets to setup/process if you want! 😄

**Comment by juruchi** [comment]
> ## Re: cyclic dependencies
> good question. I think one thing we could do is clearly define which datasets have a dependencies; for example mortality data sets, population dataset and undercounting datasets must all be computable with each other. So for the most downstream one that is v1.1 the upstream ones must at v1.1 must also be available.

I think it'll be important to map out these dependencies and plan how to handle them so that the data on the hub are compatible with one another.  I just remembered that the population data is used for some of the built environment variables and there's usually some lag time before the BEC variables are updated. There are probably other dependencies that are out there.

**Comment by usamabilal** [comment]
Great point. that map will also be very valuable...

**Comment by ran-codes** [comment]
great points!! lets move that disucssion to https://github.com/Drexel-UHC/salurbal-fair-renovations/discussions/196. 

(Keeping this issue focused on as is renovation stuff tot rack before release).

**Comment by juruchi** [comment]
@ran-codes 
> ### **In relation to this, I see that within the population folder on the non-encrypted server, there is a renovation folder. Is there a script that pulls from each of the population subfolders to populate the renovation folder?**
> If you mean `\\files.drexel.edu\colleges\SOPH\Shared\UHC\Projects\Wellcome_Trust\Data Methods Core\Dashboards\FAIR Renovations`. Don't worry about that folder it was a legacy folder used earlier one to test out codebooks but we are not using it anymore; as all codebooks and meetadta are just under version control in our GitHub repo

I was referring to ```\\files.drexel.edu\colleges\SOPH\Shared\UHC\Projects\Wellcome_Trust\Data Methods Core\Data\Population Projections Data\Renovation```. Is there a script that populates the subfolders in this folder?

**Comment by juruchi** [comment]
I've finished updating 

- Mortality #202 #203 #204 #206 
- Population #198 #199 #200 #201 
- Undercounting #205

**Comment by juruchi** [comment]
One thing I noticed was that the acknowledgements column was not showing up correctly in the base and final codebooks, but the source column was working fine

**Comment by ran-codes** [comment]
Thanks so much Jess!

 Which dataset was the acknowledgment bug/error in? (trying to reproduce).

**Comment by juruchi** [comment]
Now that I'm going through the files again, I think it's all of them

**Comment by juruchi** [comment]
One more thing: the openxlsx and xlsx libraries are not being loaded

**Comment by ran-codes** [comment]
Thansk @juruchi !!

Updates:
- acknowledgement was getting form src to codebooks beause in some src sheets the column name was misspelled (my bad).
- We added tests to import_salurbal_xlsx_src() to check for this so this won't happen again in the future
- production runs for all the dataset above.

Thanks again for your help!! 😄 


closing as these updates are all in the system.
