### ISSUE TITLE
Datset Renovation - wescores_v1.0

### ISSUE THREAD

**Issue by ran-codes** [Drexel-UHC/salurbal-fair-renovations#2]
https://github.com/Drexel-UHC/salurbal-fair-renovations/tree/main/datasets/wescores/v1.0

 ## Action Items 
  - [x] ETL setup
  - [x] define data-metadata relationships -> **linkage.csv**
  - [x] generate codebook templates -> **4.0-template__codebooks.xlsx**
  - [x] initial filling out of codebooks  -> **4.1-raw__codebooks.xlsx** - @AnaPeraltaG 
  - [x] QC of initial codebooks -> **4.2-base__codebooks.xlsx** - @ran-codes 
  - [ ] Review of base codebooks  -> **4.3-int__codebooks.xlsx**
  - [ ] QC of intermediate codebooks  -> **4.4-final__codebooks.xlsx**
  - [ ] Integration and loading into data warehouse 

## Backlog
- [ ] as of 5/15/2023: missing primary metadata for several datasets (documented below)

**Comment by ran-codes** [comment]
Thanks @AnaPeraltaG!! = ) 

---

 - [ ] generate template @juruchi . Thanks!

**Comment by juruchi** [comment]
@ran-codes quick question. In general, should all 'field' values in a linkage csv always be mapped to a 'by_' column?

**Comment by ran-codes** [comment]
@juruchi no definite answer but I'm leaning towards yes. the template contains recommended metadata fields that should be in SALURBAL data.

But if fields are unavailable (which is how I interpret @AnaPeraltaG's [raw_linkage.csv](https://github.com/Drexel-UHC/salurbal-fair-renovations/blob/main/datasets/wescores/raw__linkage.csv)) then things will break... so a hack is to just fill it out as best as your can... e.g. what relationship makes sense. Below is how I would impute missing values (replaced 1 with X to show which one was imputed).

Functionally, it means when templates are generated... and raw__codebooks are filled out those fields will be empty but that's fine. I still think all templates should have the same set of fields. Lmk what you think.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/ranli/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/ranli/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">



field | by_dataset | by_var
-- | -- | --
dataset_notes | X |  
domain |   | 1
subdomain |   | 1
var_label |   | 1
var_def |   | 1
value_type |   | 1
units |   | X
coding |   | X
strata_description |   | X
source |   | 1
limitations |   | 1
acknowledgements | X |  
file_data | 1 |  
file_codebook | 1 |  
longitudinal |   |  X
public |   | 1
censor |   | 1



</body>

</html>

**Comment by juruchi** [comment]
@AnaPeraltaG The codebook template is ready

**Comment by AnaPeraltaG** [comment]
@ran-codes 

The indicators created in this dataset (gender inequality index, women's achievement and women's empowerment) used data from vital registration, population projections, census, electoral tribunals and health surveys. How specific should I be in the data source column of the codebook? Table 3 of the protocol describe the variables that were used and their data source, and Table 4 describes the time frame of data sources that were used by country (see below). The current template does not have a by_var_iso2 tab, so I'm not sure if a general description is fine or if we want to modify the template. 



![Image](https://user-images.githubusercontent.com/115106613/236962238-9a56f1fa-24d9-4d40-ac7f-7caad3d9d770.png)



![Image](https://user-images.githubusercontent.com/115106613/236962277-bd36aa2a-e01d-47d3-bc4a-bb2e00d9a8d1.png)

**Comment by ran-codes** [comment]
@AnaPeraltaG we'll talk about this wednesday. can you add this to your list of things we need to discuss? Thanks!

For this particular issue can you collect which exact SALURBAL variables were used and store that somehow in the raw-codebook in a new sheet somewhere.

Thanks!

**Comment by AnaPeraltaG** [comment]
Thanks, @ran-codes 

Here is the codebook for this dataset. I added a new sheet where i listed the SALURBAL variables that were used.

[raw__codebook.xlsx](https://github.com/Drexel-UHC/salurbal-fair-renovations/files/11435061/raw__codebook.xlsx)

**Comment by ran-codes** [comment]
thanks ana-lu. Please remind me to bring this Wednesday if I forget.

**Comment by ran-codes** [comment]
Derived variables present in this dataset. the origin primary metadata is not yet completed and thus this dataset cannot compile (see CLI snip below`. need to wait for metadata of primary variables to finish ETL before we can compile from raw -> base for `wescore`. 

```
>   renovate_wescores_v1.0(etl)
✔ Lock file in sync with server                                                                           
✔ wescores_v1.0 data already frozen.
ℹ Importing wescores_v1.0 files.
→ Read into raw_data - wescores_L1AD_20220715.parquet

── Start Renovation wescores_v1.0 ─────────────────────────────────────
ℹ Step 1 (Variable list)
→ df_var_name validated
→ Wrote var_name.csv for wescores
✔ Success
ℹ Step 2 (Strata metadata)
→ df_strata validated.
→ Wrote strata.csv for wescores
✔ Success
ℹ Step 3 (Data formatting)
→ Valid df_data_sample
→ Wrote data for wescores
✔ Success
ℹ Step 4 (Schema + template generation)
→ Valid linkage.csv
→ Created schema.png for wescores
✔ Success
✖ valid_primary_metadata ERROR: Primary metadata missing; cannot compile metadata for derived varaibles.
→ `BTH` dataset metadata is not available.
→ `DTH` dataset metadata is not available.
→ `SEC_Census` dataset metadata is not available.
→ `SEC_marriage` dataset metadata is not available.
→ `WomenPP` dataset metadata is not available.
→ `adult_survey_prevalence` dataset metadata is not available.
ℹ Step 5a (raw -> base codebooks)
```

**Comment by AnaPeraltaG** [comment]
Hi @ran-codes. I completed the origin_var metadata for this codebook.

**Comment by ran-codes** [comment]
thanks @AnaPeraltaG !

**Comment by ran-codes** [comment]
@kam642  The codebook is ready for your review. Let us know if you have any questions!

## Action items

- [ ] Review [4.2-base__codebook.xlsx](https://github.com/Drexel-UHC/salurbal-fair-renovations/files/12029175/4.2-base__codebook.xlsx)
- [ ] Make edits as needed and save in a file called **4.3-int__codebook.xlsx**
- [ ] Comment in this issue when the final version is ready and upload the file to this issue via drag and drop

**Comment by kam642** [comment]
@ran-codes @juruchi Sorry I forgot - for variables that have other variables listed in the "origin" does this pull the public indicator based on the variables in origin?
There are a lot of pieces that go into women empowerment scores so it would be easier and less error prone if it's pulled from the origin variables.

**Comment by juruchi** [comment]
Notes from our meeting today: You can use the curly bracket notation in the source/public columns. This will allow us to pull from the appropriate source table.

**Comment by kam642** [comment]
@ran-codes @juruchi Where can I find a list of the source indicators to use the curly brackets?

**Comment by ran-codes** [comment]
@kam642 this can be found in [clean/inventory/src.xlsx](https://github.com/Drexel-UHC/salurbal-fair-renovations/raw/main/clean/inventory/src.xlsx)

**Comment by kam642** [comment]
@ran-codes @juruchi Done!
For the sources, the sources for political participation need to be added to the src.xlsx file. I included in here in curly brackets with political-participation.



[4.3-int__codebook.xlsx](https://github.com/Drexel-UHC/salurbal-fair-renovations/files/12662585/4.3-int__codebook.xlsx)

**Comment by juruchi** [comment]
I think this codebook requires some changes. The changes would have the codebook call source, public, and acknowledgement info from census, vital-registration, population, political-participation, and health-survey-adult in a by_var_iso2_year sheet. However, out of _src documents, population is the only one that uses by_key_iso2 and not by_key_iso2_year. On Wednesday's meeting can we talk about how we can adapt the source and public jinja compilation to allow for this difference?

**Comment by ran-codes** [comment]
final processing done  after 1) upgrading compile_raw...() and compile_final() functions 2) update src structure

thanks everyone!
