### ISSUE TITLE
Data Renovation - PRJG_v1.0

### ISSUE THREAD

**Issue by ran-codes** [Drexel-UHC/salurbal-fair-renovations#20]
## Dataset :  PRJG_L1AD

-  folder:  https://github.com/Drexel-UHC/salurbal-fair-renovations/tree/main/datasets/PRJG

## Action Items 
  - [x] ETL setup
  - [x] define data-metadata relationships -> **linkage.csv**
  - [x] generate codebook templates -> **4.0-template__codebooks.xlsx**
  - [x] initial filling out of codebooks  -> **4.1-raw__codebooks.xlsx**
  - [x] QC of initial codebooks -> **4.2-base__codebooks.xlsx**
  - [ ] Review of base codebooks  -> **4.3-int__codebooks.xlsx**
  - [ ] QC of intermediate codebooks  -> **4.4-final__codebooks.xlsx**
  - [ ] Integration and loading into data warehouse

**Comment by AnaPeraltaG** [comment]
Hi @ran-codes. Just letting you know that I just added Step 3 and 4 to the production folder. I confirmed with Goro which document was the most updated version of the protocol and used it to fill in some missing information. I also left a comment in the Readme document regarding the version of the protocol that i used. Thanks!

**Comment by AnaPeraltaG** [comment]
I forgot to mention this yesterday, but I was wondering if we could review Step 3 of the renovations. Even though it's a simple step to complete, I'm unsure if I have been evaluating the metadata linkages properly. Thank you!

**Comment by ran-codes** [comment]
# Re PRJG codebooks

Looks great! Thank you for sending this first draft. Two things: 1) folder structure 2) edits to the codebooks

### folder structure

I reorganized the folder slightly (as Jess/I are still finalizing how we want things structured). so apologies for shuffling things around, once we finalize things we will let the team know how to structure in the future. For now continue as is. 

- you can find you original file just moved to [PRJG_L1AD/intermediate/archive folder](https://github.com/Drexel-UHC/salurbal-fair-renovations/tree/main/datasets/PRJG_L1AD/intermediate/archive
- I converted it to .json format so we can track changes better than in .csv


### edits

I made some edits you can see the exact changes [here](https://github.com/Drexel-UHC/salurbal-fair-renovations/commit/05496d404c6d994c2a3257eb5489d10aa4220fa2) and an explaination of changes [here](https://github.com/Drexel-UHC/salurbal-fair-renovations/blob/main/datasets/PRJG_L1AD/intermediate/archive/README.md)

Lmk what you think (hope this just builds patterns to inform future renovations so we can have pre-processing).  

For now, I think I can move on with what we have and move it forward to generate codebooks for kari/goro. So no more things for you to do for this dataset.  Thanks again!!

**Comment by ran-codes** [comment]
>I forgot to mention this yesterday, but I was wondering if we could review Step 3 of the renovations. Even though it's a simple step to complete, I'm unsure if I have been evaluating the metadata linkages properly. Thank you!

Sure thing. any specific questions or do you want to have a zoom chat? (both work with me)

**Comment by AnaPeraltaG** [comment]
> > I forgot to mention this yesterday, but I was wondering if we could review Step 3 of the renovations. Even though it's a simple step to complete, I'm unsure if I have been evaluating the metadata linkages properly. Thank you!
> 
> Sure thing. any specific questions or do you want to have a zoom chat? (both work with me)

I get confused when trying to identify which codebooks i need to develop for Step 3. I know i need to create a simple codebook for all datasets, but I still get a bit confused as to why some datasets will have a by_country codebook (but not all of them) when we do have data by country in all datasets. For instance, the LE data had a _simple_ and _by_country_ codebook, but the BEC only had a _simple_ codebook. 

The other thing that is still not very clear to me is how to identify if all metadata have simple linkage or not. The template we have assumes everything is simple, but I'm not sure how to evaluate if this is true for each field.

**Comment by ran-codes** [comment]
@AnaPeraltaG great questions . Since these questions are not so much dataset specific but rather about the renovation process I have moved them to their own discussion.

> re: I get confused when trying to identify which codebooks i need to develop for Step 3
see #43

> re: The other thing that is still not very clear to me is how to identify if all metadata have simple linkage or not.
see #42

**Comment by ran-codes** [comment]
Thanks again @AnaPeraltaG!

Ready to pass on to KM/GY; few pending items to discuss  at 3/8.
- waiting on `population` src tables from #41 
- need to discuss a project-wide `spatial` source

**Comment by ran-codes** [comment]
@juruchi . I made some changes to templates so can you go through the raw -> process again to check things for PRJG.  Thanks!

**Comment by ran-codes** [comment]
@juruchi the issue was we just didn't have source for or a reliable `public` values for the variables in this dataset. I have created the `raw__codebook` as per some of the pervious work by Ana-lu but can you 

- [ ] fill out source and public in raw__codebook
- [ ] then process to int 
- [ ] hand off to Goro for verfication

**Comment by juruchi** [comment]
@goro-yamada The codebook is ready for your review. Let us know if you have any questions!

## Action items

- [ ] Review **datasets/PRJG/intermediate/3-int__codebook.xlsx**
- [ ] Make edits as needed and save in a file called **4-final__codebook.xlsx**
- [ ] Comment in this issue when the final version is ready and upload the file to this issue

**Comment by goro-yamada** [comment]
@juruchi I am reviewing the assigned table and have some comments for you.
1. by_var_iso2 sheet: The source should be the same within country. It does not make sense that we need to review by variable.
2. Thes source / public / censor variables should be the same as the total population data. Is there any way to cinchonize variables in these datasets. This will be the same for population data stratified by city, year, age and sex.
3. Related to #1 and #2, we are introducing a potential human error. Whereas source / public / censor should be consistent within country, by reviewing and editing one by one, they can be inconsistent if the reviewer makes mistakes. E.g., I forget updating one variable, and these values become inconsistent within country.
4. Do we still use public and censor variables separately?

**Comment by juruchi** [comment]
@goro-yamada The following are responses to your questions. These are changes I will be working on, so I'll unassign you this task for the time being. I'll let you know once things are ready for your review.

1. Source will be changed to differ by country only.
2. Since the PRJS datasets are the base datasets from which PRJ, PRJT, and PRJG are created, we will use the new internal codebook column 'variable_origin' to sync source and public across the population projection datasets.
3. The use of 'variable_origin' will reduce the number of places source and public need to be filled out for the population projection datasets, reducing potential human error. However, potential human error when filling out the public column still exists. Goro, we can talk more generally about setting up redundancies for the vital statistics and census data so that potential errors in 'public' are caught.
4. Public has switched from binary to categorical, so we are no longer using censor.

**Comment by ran-codes** [comment]
@goro-yamada The codebook is ready for your review. Details on codebook fields can be found [here](https://github.com/Drexel-UHC/salurbal-fair-renovations/raw/main/documents/templates/_template_details.xlsx) Let us know if you have any questions!

## Action items

- [ ] Review **UPDATED CODEBOOK**  [4.2-base__codebook.xlsx](https://github.com/Drexel-UHC/salurbal-fair-renovations/files/11553997/4.2-base__codebook.xlsx)
- [ ] Review [associated sources for {{population}} ](https://github.com/Drexel-UHC/salurbal-fair-renovations/raw/main/datasets/_src/src__population.xlsx)
- [ ] Make edits as needed and save in a file called **4.3-int__codebook.xlsx**
- [ ] Comment in this issue when the final version is ready and upload the file to this issue via drag and drop

**Comment by ran-codes** [comment]
Thanks everyone for hard work. closing issue!!

🍰
