### ISSUE TITLE
On boarding Goro to GitHub

### ISSUE THREAD

**Issue by ran-codes** [Drexel-UHC/salurbal-fair-renovations#31]
Goro is new to GitHub.  I want to check that we can communicate using an issue. 

## Action Items 

- [ ] @goro-yamada please comment in this issue and tell us your favorite food.

**Comment by ran-codes** [comment]
testing email @goro-yamada

**Comment by ran-codes** [comment]
@goro-yamada another test for goro's email; please respond if you get this. thanks!!

**Comment by ran-codes** [comment]
@juruchi just testing if GitHub is emailing you. Can you comment below if so!

Thanks!!

**Comment by juruchi** [comment]
Got the email!

**Comment by ran-codes** [comment]
@goro-yamada test. (reply if you get this)

**Comment by ran-codes** [comment]
@goro-yamada
