### ISSUE TITLE
human friendly codebook format?

### ISSUE THREAD

**Issue by ran-codes** [Drexel-UHC/salurbal-fair-renovations#45]
### Discussed in https://github.com/Drexel-UHC/salurbal-fair-renovations/discussions/44

<div type='discussions-op-text'>

<sup>Originally posted by **ran-codes** March  1, 2023</sup>
@kam642 can you upload a few exmaples of good user friendly code. so we can start thinkingbabout bhow to operationlzieing our machine-readable codebook in a more user friendly fashion. </div>

**Comment by kam642** [comment]
@ran-codes I think we just need to take the info we have with the codebooks you're creating and make them output in a way that removes fields they typical user doesn't need and make sure all variables that are in the dataset are in the codebook, including ID number variables.
I look the final version of air pollution and formatted to look like something that would be more appealing to look at for users. Let me know if you have questions.



[example user friendly codebook.xlsx](https://github.com/Drexel-UHC/salurbal-fair-renovations/files/10871971/example.user.friendly.codebook.xlsx)

**Comment by ran-codes** [comment]
@kam642 that sounds good. Follow up questions: 

- How do we want to handle the more complex data source taht vary by country or year (just squeeze all that infor into a single cell?)
- provide an example user friendly codebookfor LEMEDIAN

**Comment by kam642** [comment]
@ran-codes Can you send me a link to where I can find the final version that we currently have for renovations?

**Comment by ran-codes** [comment]
@kam642 they can be found [LEMEDIAN  > intermediate folder](https://github.com/Drexel-UHC/salurbal-fair-renovations/tree/main/datasets/LEMEDIAN_L1/intermediate). The farthest along we got so far is the `int__codebooks`. THey are mostly done just waiting on population sources that jess is working on. 

The two files you want are:
- [int__codebook_by_var.csv](https://github.com/Drexel-UHC/salurbal-fair-renovations/blob/main/datasets/LEMEDIAN_L1/intermediate/int__codebook_by_var.csv)
- [int__codebook_by_var_iso2_year.csv](https://github.com/Drexel-UHC/salurbal-fair-renovations/blob/main/datasets/LEMEDIAN_L1/intermediate/int__codebook_by_var_iso2_year.csv)

**Comment by kam642** [comment]
@ran-codes attaching 2 new examples. one for easy, one for hard. Would it be possible to do more like this format?

[hard example user friendly codebook.xlsx](https://github.com/Drexel-UHC/salurbal-fair-renovations/files/10873945/hard.example.user.friendly.codebook.xlsx)
[easy example user friendly codebook.xlsx](https://github.com/Drexel-UHC/salurbal-fair-renovations/files/10873946/easy.example.user.friendly.codebook.xlsx)

**Comment by ran-codes** [comment]
@kam642 these two look like the same to me both are APS and no LEMEDIAN?

**Comment by ran-codes** [comment]
@kam642 thanks. this make perfect sense! Will add this to list of things to do. Will give updates as they come.

**Comment by ran-codes** [comment]
@kam642 you can check the generated odebook: for each dataset there should be a {dataset_id}_mmddYYY.xlsx file.  Clikc th folders here: https://github.com/Drexel-UHC/salurbal-fair-renovations/tree/main/datasets

**Comment by kam642** [comment]
@ran-codes Looks great! Exactly what I was thinking.

2 things: Remove "codebook file" because this isn't relevant for the human friendly.
The number of columns is currently 2 fewer because didn't count ISO2 and SALID1.

**Comment by ran-codes** [comment]
updates made. closing for now. will add mult-level features later.
