### ISSUE TITLE
renovation - DTHI

### ISSUE THREAD

**Issue by ran-codes** [Drexel-UHC/salurbal-fair-renovations#65]
https://github.com/Drexel-UHC/salurbal-fair-renovations/tree/main/datasets/DTHI/v1.0

## Action Items 

  - [x] ETL setup
  - [x] define data-metadata relationships -> **linkage.csv**
  - [x] generate codebook templates -> **4.0-template__codebooks.xlsx**
  - [x] initial filling out of codebooks  -> **4.1-raw__codebooks.xlsx**
  - [x] QC of initial codebooks -> **4.2-base__codebooks.xlsx**
  - [ ] Review of base codebooks  -> **4.3-int__codebooks.xlsx**
  - [ ] QC of intermediate codebooks  -> **4.4-final__codebooks.xlsx**
  - [ ] Integration and loading into data warehouse

**Comment by goro-yamada** [comment]
@juruchi I did not see any issues in the two files.

**Comment by juruchi** [comment]
The final codebook has been generated. Thanks everyone!
