### ISSUE TITLE
LE_L1_v1.0

### ISSUE THREAD

**Issue by ran-codes** [Drexel-UHC/salurbal-fair-renovations#68]
https://github.com/Drexel-UHC/salurbal-fair-renovations/tree/main/datasets/LE_L1/v1.0

 ## Action Items 
  - [x] ETL setup
  - [x] define data-metadata relationships -> **linkage.csv**
  - [x] generate codebook templates -> **4.0-template__codebooks.xlsx**
  - [x] initial filling out of codebooks  -> **4.1-raw__codebooks.xlsx**
  - [x] QC of initial codebooks -> **4.2-base__codebooks.xlsx**
  - [x] Review of base codebooks  -> **4.3-int__codebooks.xlsx**
  - [ ] QC of intermediate codebooks  -> **4.4-final__codebooks.xlsx**
  - [ ] Integration and loading into data warehouse

**Comment by ran-codes** [comment]
on hold as I am not sure if we want to include this in the datawarehouse. 

i assume its just iterations from simulations which we then summarize in LE_MEDIAN. So any downstream research synthesis or applications will only utilize LE_MEDIAN. 

LE_MEDIAN should stay within the repository of the LE working groups project. 

@usamabilal thoughts?

**Comment by usamabilal** [comment]
Hmm...good question. Models should use LE_L1, not LE_MEDIAN, but descriptive stuff should use LE_MEDIAN. I would include it, but we may need an explanation of its use.

**Comment by AnaPeraltaG** [comment]
Hi @juruchi. Linkage.csv is ready to review. Thanks!

**Comment by juruchi** [comment]
@ran-codes @kam642  Data processing for this dataset includes iterations of LE as strata, which means that the template codebook is set to have a by_var_strata sheet with over 27,000 rows. From both a renovator and end-user perspective, is this the best codebook format for the data or is there another option that can be used?

**Comment by ran-codes** [comment]
@juruchi i would move strata_description to by_dataset. I think we just need a description what each strata in this case iternation means. After updating linkage codebook won't have a by_strata type sheet. **In summary, no need for strata level metadata for this dataset. **

**Comment by juruchi** [comment]
Since this dataset also has sex and age strata, should the iteration data be handled similarly to how confidence interval data is handled in other datasets?

**Comment by ran-codes** [comment]
I'm leaning towards yes... as its not a population strata which is what 'stata' is meant to capture. Instead this would make more sense as an attribute of the data (e.g. which iteration the sample is from).  We can discuss this with the group on Wednesday to make sure everyone is on board.

But implementation wise I think @juruchi if you have time do you want to take a stab at it? (or let me know if you prefer me to do it). Just a rough protocol in my mind right now:

- remove iteration from df_var_name, df_strata,
- op. 'iteration' as a column in df_data.
- update df_data export func to allow this (if there are failed unit tests).

**Comment by juruchi** [comment]
Would you mind taking a look at this?

**Comment by ran-codes** [comment]
okay. lets run this through kari on wednesday. then I'll put together a PR for this.

**Comment by usamabilal** [comment]
Since I created this data, let me know if there's anything you'd like to run by me...

**Comment by ran-codes** [comment]
@usamabilal  data and metadata won't change. But we just want to clarify how `iteration` should be captured within our data system.
![image]()

- option 1: as metadata within  `strata`
   - this information is stored in codebooks  within the `strata` columns
   - usually `strata` refers to population strata so iteration might not fit here
   - `strata`  will be displayed as [this on the portal](https://github.com/Drexel-UHC/salurbal-fair-renovations/assets/45013044/8cdb1c3d-dea3-4aad-8e53-5f2f0dada9bb); having 27,000 rows. in this table doesn't seem useful.
- option 2: as a `data` attribute so
   - This information is stored within data files as a column `iteration`.
   - These types of columns capture attributes of the data... other type of these columns include `value_uci`, `value_lci`.

We are thinking option 2 is better for capturing `iteration`. lmk what you think!

**Comment by usamabilal** [comment]
Definitely 2! Makes a lot more sense to me

**Comment by ran-codes** [comment]
iteration metadta removed from `df_strata` and into `df_data` as data attribute `value_iteration`.

@AnaPeraltaG codebook templates are ready for you to fill out!

**Comment by AnaPeraltaG** [comment]
@ran-codes @juruchi 

The codebook is ready to review :)

**Comment by ran-codes** [comment]
thank you @AnaPeraltaG 😄

**Comment by ran-codes** [comment]
@goro-yamada  The codebook is ready for your review. Details on codebook fields can be found [here](https://github.com/Drexel-UHC/salurbal-fair-renovations/raw/main/documents/templates/_template_details.xlsx) Let us know if you have any questions!

## Action items

- [x] Review [4.2-base__codebook.xlsx](https://github.com/Drexel-UHC/salurbal-fair-renovations/files/12292229/4.2-base__codebook.xlsx)
- [x] Make edits as needed and save in a file called **4.3-int__codebook.xlsx**
- [x] Comment in this issue when the final version is ready and upload the file to this issue via drag and drop

**Comment by goro-yamada** [comment]
@ran-codes 
[4.3-int__codebook.xlsx](https://github.com/Drexel-UHC/salurbal-fair-renovations/files/12306683/4.3-int__codebook.xlsx)

**Comment by ran-codes** [comment]
thank you goro 😄

**Comment by ran-codes** [comment]
intermediate codebooks passed testing + final codbeook processed.

Closing. Thanks everyone  🍸 !
