### ISSUE TITLE
renovation APS_MONTH

### ISSUE THREAD

**Issue by ran-codes** [Drexel-UHC/salurbal-fair-renovations#82]
https://github.com/Drexel-UHC/salurbal-fair-renovations/tree/main/datasets/APS_MONTH/v1.0

## Action Items 
  - [x] ETL setup
  - [x] define data-metadata relationships -> **linkage.csv**
  - [x] generate codebook templates -> **4.0-template__codebooks.xlsx**
  - [x] initial filling out of codebooks  -> **4.1-raw__codebooks.xlsx**
  - [x] QC of initial codebooks -> **4.2-base__codebooks.xlsx**
  - [x] Review of base codebooks  -> **4.3-int__codebooks.xlsx**
  - [x] QC of intermediate codebooks  -> **4.4-final__codebooks.xlsx**
  - [ ] Integration and loading into data warehouse

**Comment by dianahiguera** [comment]
I arrived at this, following your instructions from last week. I will wait for your directives. Just letting you know I am here @ran-codes

**Comment by ran-codes** [comment]
@dianahiguera Thanks for the reminder 😄 

setup is done and ready for you to start renovating.
- repo: https://github.com/Drexel-UHC/salurbal-fair-renovations/tree/main/datasets/APS_MONTH/v1.0 
- server: \\files.drexel.edu\colleges\SOPH\Shared\UHC\Projects\Wellcome_Trust\Data Methods Core\Data\Air_Pollution

**Comment by dianahiguera** [comment]
@juruchi @ran-codes Linkage done :)

**Comment by juruchi** [comment]
@dianahiguera template has been generated

**Comment by dianahiguera** [comment]
@ran-codes raw_codebook ready for review

**Comment by ran-codes** [comment]
@kam642  The codebook is ready for your review. Details on codebook fields can be found [here](https://github.com/Drexel-UHC/salurbal-fair-renovations/raw/main/documents/templates/_template_details.xlsx) Let us know if you have any questions!

## Action items


- [ ] Review [4.2-base__codebook.xlsx](https://github.com/Drexel-UHC/salurbal-fair-renovations/files/12303474/4.2-base__codebook.xlsx)
- [ ] Make edits as needed and save in a file called **4.3-int__codebook.xlsx**
- [ ] Comment in this issue when the final version is ready and upload the file to this issue via drag and drop

**Comment by juruchi** [comment]
Copy APS codebook link

**Comment by ran-codes** [comment]
@kam642  The codebook is ready for your review. Details on codebook fields can be found [here in the sheet named 4-codebook.csv ](https://github.com/Drexel-UHC/salurbal-fair-renovations/raw/main/documents/templates/_template_details.xlsx) Let us know if you have any questions!

Here is [APS_v2.0_final__codebook.xlsx](https://github.com/Drexel-UHC/salurbal-fair-renovations/files/12362368/4.4-final__codebook.xlsx)

## Action items



- [ ] Review [4.2-base__codebook.xlsx](https://github.com/Drexel-UHC/salurbal-fair-renovations/files/12362366/4.2-base__codebook.xlsx)
- [ ] Make edits as needed and save in a file called **4.3-int__codebook.xlsx**
- [ ] Comment in this issue when the final version is ready and upload the file to this issue via drag and drop

**Comment by kam642** [comment]
@ran-codes @juruchi Done!



[4.3-int__codebook.xlsx](https://github.com/Drexel-UHC/salurbal-fair-renovations/files/12599177/4.3-int__codebook.xlsx)

**Comment by juruchi** [comment]
Final codebook generated - closing this issue. Thank you everyone!
