### ISSUE TITLE
Kari to review domain/subdomain before june release

### ISSUE THREAD

**Issue by ran-codes** [Drexel-UHC/salurbal-fair-renovations#96]
> @ran-codes Before we release in Jun, remind me to review the domains/subdomains to see if any edits are needed in the descriptions. We've added more data so some of the descriptions need some slight modification.
> 
> _Originally posted by @kam642 in https://github.com/Drexel-UHC/salurbal-fair-renovations/issues/9#issuecomment-1539978160_
            
**reminder issue. will fill out later**

### Action Items

- [x]  DMC review
- [x] BEC Review
- [x] Decide on order (` Data> about: change order of domains for something logical (row 2)` from https://github.com/Drexel-UHC/salurbal-project-dashboard/issues/335

**Comment by AnaPeraltaG** [comment]
- Review the subdomain of variables BECADTYPEL3, BECADAREAL3 and BECGEOFLAL3 in codebook #23. 
- Review the subdomain of variables in #4 
-

**Comment by kam642** [comment]
@ran-codes I reviewed the text of domains/subdomains on the website and made some edits. Sending to Ana DR and Daniel/Olga Lucia for final reviews and some edits. Attached doc is not final yet.


[SALURBAL Domains and subdomains.docx](https://github.com/Drexel-UHC/salurbal-fair-renovations/files/11668201/SALURBAL.Domains.and.subdomains.docx)

**Comment by ran-codes** [comment]
great thanks @kam642. Will wait for the final version before I amke changes.

**Comment by ran-codes** [comment]
@kam642 something to review: as I am looking through the BEC raw codebook. Is there are a lot of things with the subdomain 'Urban Form Metrics' which is not in the word doc. Can you ask Olga-lucia and Daniel if this is something they want to add.

**Comment by kam642** [comment]
@ran-codes Reminder to review sent to Ana, Daniel, and Olga Lucia. I gave them a drop dead date of noon on Tues, June 27.

**Comment by kam642** [comment]
@ran-codes See attached with a couple updates. BEC team responded that what we currently have in here are fine. Olga Lucia is supposed to respond about the Urban Form Metrics but I do not have a response from her yet. Will send as soon as I have it.
I did not get a response from Ana so I will assume she is ok with this.


[SALURBAL Domains and subdomains.docx](https://github.com/Drexel-UHC/salurbal-fair-renovations/files/11893348/SALURBAL.Domains.and.subdomains.docx)

**Comment by kam642** [comment]
@ran-codes Received edits from Ana. Attached here. Still waiting for BEC.



[SALURBAL Domains and subdomainsadr.docx](https://github.com/Drexel-UHC/salurbal-fair-renovations/files/11982687/SALURBAL.Domains.and.subdomainsadr.docx)

**Comment by ran-codes** [comment]
Thanks @kam642! Will wait for the BEC version then make updates.

**Comment by kam642** [comment]
@ran-codes I sent another email to Daniel and Olga Lucia to finalize by end of this week.

**Comment by ran-codes** [comment]
thanks @kam642!!

**Comment by juruchi** [comment]
Can we add mortality or something similar as a subdomain of Mortality. Currently, we don't have a good subdomain that encompasses the mortality count datasets.

**Comment by usamabilal** [comment]
Could do by outcome (rates counts or life expectancy ) or by cause (all cause vs cause specific)
________________________________

**Comment by kam642** [comment]
@ran-codes I finally got responses from BEC on domains! See here for the final versions.

@juruchi I added "Mortality Counts" as a subdomain so you can use that for comment above.

[SALURBAL.Domains.and.subdomainsFinal.docx](https://github.com/Drexel-UHC/salurbal-fair-renovations/files/12803428/SALURBAL.Domains.and.subdomainsFinal.docx)

**Comment by ran-codes** [comment]
thanks kari. updated on backend. Will deploy to portal next week.
